apiVersion: v1
kind: Pod
metadata:
  name: kube-podmaster
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: scheduler-elector
    image: ${PODMASTER}
    command:
    - /podmaster
    - --etcd-servers=http://etcd.k8s:2379
    - --key=scheduler
    - --source-file=/src/manifests/kube-scheduler.yml
    - --dest-file=/dst/manifests/kube-scheduler.yml
    volumeMounts:
    - mountPath: /src/manifests
      name: manifest-src
      readOnly: true
    - mountPath: /dst/manifests
      name: manifest-dst
  - name: controller-manager-elector
    image: ${PODMASTER}
    command:
    - /podmaster
    - --etcd-servers=http://etcd.k8s:2379
    - --key=controller
    - --source-file=/src/manifests/kube-controller-manager.yml
    - --dest-file=/dst/manifests/kube-controller-manager.yml
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /src/manifests
      name: manifest-src
      readOnly: true
    - mountPath: /dst/manifests
      name: manifest-dst
  volumes:
  - hostPath:
      path: /srv/kubernetes/manifests
    name: manifest-src
  - hostPath:
      path: /etc/kubernetes/manifests
    name: manifest-dst
